# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddIngredients.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addIngredients(object):
    def setupUi(self, addIngredients):
        addIngredients.setObjectName("addIngredients")
        addIngredients.resize(323, 287)
        addIngredients.setToolTipDuration(-1)
        self.verticalLayout = QtWidgets.QVBoxLayout(addIngredients)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputsLayout = QtWidgets.QVBoxLayout()
        self.inputsLayout.setObjectName("inputsLayout")
        self.inputLayout = QtWidgets.QHBoxLayout()
        self.inputLayout.setObjectName("inputLayout")
        self.lineEdit = QtWidgets.QLineEdit(addIngredients)
        self.lineEdit.setObjectName("lineEdit")
        self.inputLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(addIngredients)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("padding: 5px 10px; color: red;")
        self.pushButton.setObjectName("pushButton")
        self.inputLayout.addWidget(self.pushButton)
        self.inputsLayout.addLayout(self.inputLayout)
        self.verticalLayout.addLayout(self.inputsLayout)
        self.pushButton_2 = QtWidgets.QPushButton(addIngredients)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(addIngredients)
        QtCore.QMetaObject.connectSlotsByName(addIngredients)

    def retranslateUi(self, addIngredients):
        _translate = QtCore.QCoreApplication.translate
        addIngredients.setWindowTitle(_translate("addIngredients", "AddIngredients"))
        self.pushButton.setText(_translate("addIngredients", "Delete"))
        self.pushButton_2.setText(_translate("addIngredients", "Add Ingredient"))
