# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddIngredient.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addIngredient(object):
    def setupUi(self, addIngredient):
        addIngredient.setObjectName("addIngredient")
        addIngredient.resize(400, 66)
        self.horizontalLayout = QtWidgets.QHBoxLayout(addIngredient)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ingredientInput = QtWidgets.QLineEdit(addIngredient)
        self.ingredientInput.setObjectName("ingredientInput")
        self.horizontalLayout.addWidget(self.ingredientInput)
        self.deleteBtn = QtWidgets.QPushButton(addIngredient)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteBtn.sizePolicy().hasHeightForWidth())
        self.deleteBtn.setSizePolicy(sizePolicy)
        self.deleteBtn.setStyleSheet("padding: 5px 10px; color: red;")
        self.deleteBtn.setObjectName("deleteBtn")
        self.horizontalLayout.addWidget(self.deleteBtn)

        self.retranslateUi(addIngredient)
        QtCore.QMetaObject.connectSlotsByName(addIngredient)

    def retranslateUi(self, addIngredient):
        _translate = QtCore.QCoreApplication.translate
        addIngredient.setWindowTitle(_translate("addIngredient", "AddIngredient"))
        self.deleteBtn.setText(_translate("addIngredient", "Delete"))
