# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'barcodePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_barcodePage(object):
    def setupUi(self, barcodePage):
        barcodePage.setObjectName("barcodePage")
        barcodePage.resize(271, 315)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(barcodePage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(barcodePage)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.barcodeTitle = QtWidgets.QLabel(barcodePage)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.barcodeTitle.setFont(font)
        self.barcodeTitle.setObjectName("barcodeTitle")
        self.verticalLayout.addWidget(self.barcodeTitle)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.barcodeInput = QtWidgets.QLineEdit(barcodePage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.barcodeInput.setFont(font)
        self.barcodeInput.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.barcodeInput.setText("")
        self.barcodeInput.setObjectName("barcodeInput")
        self.horizontalLayout.addWidget(self.barcodeInput)
        self.submit = QtWidgets.QPushButton(barcodePage)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.horizontalLayout.addWidget(self.submit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.errorMsg = QtWidgets.QLabel(barcodePage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorMsg.sizePolicy().hasHeightForWidth())
        self.errorMsg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        self.errorMsg.setFont(font)
        self.errorMsg.setStyleSheet("color: red;")
        self.errorMsg.setObjectName("errorMsg")
        self.verticalLayout.addWidget(self.errorMsg)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(barcodePage)
        QtCore.QMetaObject.connectSlotsByName(barcodePage)

    def retranslateUi(self, barcodePage):
        _translate = QtCore.QCoreApplication.translate
        barcodePage.setWindowTitle(_translate("barcodePage", "BarcodePage"))
        self.label.setText(_translate("barcodePage", "Enter a Barcode"))
        self.barcodeTitle.setText(_translate("barcodePage", "Enter a barcode to search for ingredients"))
        self.submit.setText(_translate("barcodePage", "Submit"))
        self.errorMsg.setText(_translate("barcodePage", "ErrorMessage"))
