# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowSymptomsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_showSymptomsPage(object):
    def setupUi(self, showSymptomsPage):
        showSymptomsPage.setObjectName("showSymptomsPage")
        showSymptomsPage.resize(309, 265)
        self.verticalLayout = QtWidgets.QVBoxLayout(showSymptomsPage)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(showSymptomsPage)
        QtCore.QMetaObject.connectSlotsByName(showSymptomsPage)

    def retranslateUi(self, showSymptomsPage):
        _translate = QtCore.QCoreApplication.translate
        showSymptomsPage.setWindowTitle(_translate("showSymptomsPage", "ShowSymptomsPage"))
