# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowFoodsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_showFoodsPage(object):
    def setupUi(self, showFoodsPage):
        showFoodsPage.setObjectName("showFoodsPage")
        showFoodsPage.resize(360, 638)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(showFoodsPage.sizePolicy().hasHeightForWidth())
        showFoodsPage.setSizePolicy(sizePolicy)
        showFoodsPage.setMaximumSize(QtCore.QSize(360, 50000))
        self.verticalLayout = QtWidgets.QVBoxLayout(showFoodsPage)
        self.verticalLayout.setObjectName("verticalLayout")

        self.retranslateUi(showFoodsPage)
        QtCore.QMetaObject.connectSlotsByName(showFoodsPage)

    def retranslateUi(self, showFoodsPage):
        _translate = QtCore.QCoreApplication.translate
        showFoodsPage.setWindowTitle(_translate("showFoodsPage", "ShowFoodsPage"))
