# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShowFoodsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_showFoodsPage(object):
    def setupUi(self, showFoodsPage):
        showFoodsPage.setObjectName("showFoodsPage")
        showFoodsPage.resize(360, 640)
        showFoodsPage.setMaximumSize(QtCore.QSize(360, 640))
        self.verticalLayout = QtWidgets.QVBoxLayout(showFoodsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(showFoodsPage)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(showFoodsPage)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(showFoodsPage)
        QtCore.QMetaObject.connectSlotsByName(showFoodsPage)

    def retranslateUi(self, showFoodsPage):
        _translate = QtCore.QCoreApplication.translate
        showFoodsPage.setWindowTitle(_translate("showFoodsPage", "ShowFoodsPage"))
        self.label.setText(_translate("showFoodsPage", "Test"))
        self.label_2.setText(_translate("showFoodsPage", "TextLabel"))
